%YAML:1.0

File.version: "1.0"

Camera.type: "Rectified"

# Rectified Camera calibration and distortion parameters
Camera.fx: 412.45037841796875
Camera.fy: 412.45037841796875
Camera.cx: 422.34375
Camera.cy: 241.32501220703125

Stereo.b: 0.0507745018

# Camera resolution
Camera.width: 848
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# Grayscale IR, this parameter is effectively ignored
Camera.RGB: 0

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0

# ORB parameters - initially keep D435i defaults
ORBextractor.nFeatures: 1250
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

# Viewer
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0